[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[env.production]
  environment = {VITE_PASSWORDENCRIPT = "2222", VITE_PASSWORD_READ = "1111", VITE_PASSWORD_WRITE = "0000"}
