export const PROGRAMS = [
    {name: "Arquitectura"},
    {name: "Artes"},
    {name: "Artes plasticas y visuales"},
    {name: "Bioquimica"},
    {name: "Ciencias"},
    {name: "Ciencias Económicas y Administrativas"},
    {name: "Comercio Internacional"},
    {name: "Contaduria publica "},
    {name: "Derecho"},
    {name: "Dideño grafico"},
    {name: "Diseño industrial"},
    {name: "Economía"},
    {name: "Educación"},
    {name: "Enfermería"},
    {name: "Ingeneiria Mecanica "},
    {name: "Ingeniera de Software"},
    {name: "Ingeniera Electomecanica "},
    {name: "Ingeniería Ambiental"},
    {name: "Ingenieria Biomedica"},
    {name: "Ingenieria Civil"},
    {name: "Ingeniería de Sistemas"},
    {name: "Ingenieria de Sistemas y Computación "},
    {name: "Ingenieria Electronica"},
    {name: "Ingenieria en control y automatización industrial"},
    {name: "Ingeniería Industrial"},
    {name: "Ingeniería Mecánica Electrónica y Biomédica"},
    {name: "Ingenieria mecatronica"},
    {name: "Licenciatura en  educacion infantil "},
    {name: "Licenciatura en artes escénicas"},
    {name: "Licenciatura en ciencias naturales y educacion ambiental "},
    {name: "Licenciatura en español e inglés"},
    {name: "Licenciatura en matemáticas"},
    {name: "Medicina"},
    {name: "Medicina Veterinaria"},
    {name: "Musica"},
    {name: "Odontología"},
    {name: "Optometría"},
    {name: "profesional en danzas y teatro"},
    {name: "Psicología"},
    {name: "Tecnologia en contrucciond e software"},
    {name: "Tecnologia en mecanica automotriz"},
    {name: "Terapias Psicosociales"},
    {name: "Trabajo social"},
    {name: "DOCTORADO EN CIENCIA APLICADA"},
    {name: "DOCTORADO EN CIENCIAS NATURALES Y EXACTAS"},
    {name: "ESPECIALIZACIÓN EN ACTUARIA"},
    {name: "MAESTRÍA EN BIOQUÍMICA"},
    {name: "MAESTRÍA EN INGENIERIA FISICA"},
    {name: "MAESTRÍA EN METROLOGÍA"},
    {name: "DOCTORADO EN CIENCIAS DE LA SALUD"},
    {name: "ESPECIALIZACION EN ENFERMERIA MATERNO PERINATAL"},
    {name: "ESPECIALIZACIÓN EN ORTODONCIA"},
    {name: "ESPECIALIZACIÓN EN PERIODONCIA"},
    {name: "ESPECIALIZACIÓN EN SEGURIDAD Y SALUD EN EL TRABAJO"},
    {name: "MAESTRIA EN CUIDADOS PALIATIVOS"},
    {name: "MAESTRIA EN PREVENCIÓN Y GESTIÓN DEL RIESGO DE LA DROGODEPENDENCIA"},
    {name: "MAESTRÍA EN SALUD COLECTIVA"},
    {name: "DOCTORADO EN EDUCACION MATEMATICA"},
    {name: "DOCTORADO EN EDUCACIÓN"},
    {name: "MAESTRÍA EN DIDÁCTICA DE LAS ARTES ESCÉNICAS"},
    {name: "MAESTRÍA EN EDUCACION"},
    {name: "MAESTRÍA EN EDUCACION MATEMATICA"},
    {name: "ESPECIALIZACION EN GOBIERNO DE DATOS"},
    {name: "ESPECIALIZACIÓN EN INGENIERIA DE SOFTWARE"},
    {name: "ESPECIALIZACIÓN EN INSTRUMENTACIÓN ELECTRÓNICA Y BIOMÉDICA"},
    {name: "ESPECIALIZACIÓN EN SISTEMAS DE INFORMACION GEOGRAFICA"},
    {name: "MAESTRÍA EN AUTOMATIZACIÓN E INSTRUMENTACIÓN"},
    {name: "MAESTRÍA EN GESTIÓN DE LA INFRAESTRUCTURA"},
    {name: "MAESTRÍA EN INGENIERIA DE BIOPROCESOS"},
    {name: "ESPECIALIZACIÓN EN ADMINISTRACION PUBLICA"},
    {name: "ESPECIALIZACIÓN EN AUDITORIA DE SISTEMAS"},
    {name: "ESPECIALIZACIÓN EN GERENCIA DEL DESARROLLO HUMANO Y ORGANIZACIONAL"},
    {name: "ESPECIALIZACIÓN EN GESTION FINANCIERA"},
    {name: "MAESTRÍA EN ECONOMIA DE LA SALUD"},
    {name: "MAESTRÍA EN GERENCIA FINANCIERA Y TRIBUTARIA"},
    {name: "ESPECIALIZACIÓN EN DERECHO ADMISTRATIVO Y PROCEDIMIENTO ADMINISTRAVO"},
    {name: "MAESTRIA EN CRIMINOLOGÍA Y CONFLICTO"},
    {name: "MAESTRIA EN EQUIDAD DE GENERO"},
    {name: "MAESTRIA EN POLÍTICAS PÚBLICAS MEDIOAMBIENTALES"},
    {name: "MAESTRIA EN PRATICAS ARTISTICAS EN HABITAT"},
    {name: "MAESTRÍA EN DERECHO DE FAMILIA"},
    {name: "MAESTRÍA EN MEDIACIÓN FAMILIAR"},
    {name: "MAESTRÍA EN MIGRACIONES E INTERCULTURALIDAD"},
    {name: "MAESTRÍA EN ARTE SONORO"},
    {name: "MAESTRÍA EN BIENESTAR ANIMAL"},
];